kind: pipeline
name: default

services:  
  selenium:
          image: selenium/standalone-chrome:3.141.59-vanadium 
platform:
  arch: amd64
  os: linux

pipeline:
  test:
    image: alpine/git
    image: java:8-jdk
    pull: true
    commands:
      - java -version
