kind: pipeline
type: docker
name: linux-amd64

services:
   -  name: hub
      image: selenium/hub:3.141.59-xenon
      image: selenium/node-chrome:3.141.59-xenon
        environment:
          HUB_HOST: hub
          HUB_PORT: 4444
    
platform:
  arch: amd64
  os: linux

steps:
  -  name: test
     image: alpine/git
     image: openjdk:11.0.2
     pull: true
     
     commands:

       - java -version
       - chmod 777 ./lib/Drivers/chromedriver
       - chmod 777 ./Run.command
       - ./Run.command -run -project_location "Projects/DemoProject" -release "cits" -testset "BasicWebFlow_Environment1"
when:
    event:
      - push
      - tag
