kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
services:  
  image: selenium/hub
  chrome:
    image: selenium/node-chrome
      

steps:
  -  name: test
     image: alpine/git
     image: openjdk:11.0.2
     image: selenium/standalone-chrome
     pull: true
     
     commands:
       - chmod 777 ./Run.command
       - chmod 777 ./lib/Drivers/chromedriver
       - ./Run.command -run -project_location "Projects/DemoProject" -scenario "AngularJS_Support" -testcase "AngularJS_Test" -browser "Firefox"
when:
    event:
      - push
      - tag
