kind: pipeline
name: default

services:
  selenium:
    image: selenium/hub
  chrome:
    image: selenium/node-chrome:latest
    environment:
      HUB_PORT_4444_TCP_ADDR: selenium
      HUB_PORT_4444_TCP_PORT: "4444"
  firefox:
    image: selenium/node-firefox:latest
    environment:
      HUB_PORT_4444_TCP_ADDR: latest
      HUB_PORT_4444_TCP_PORT: "4444"
      DISPLAY: ":98.0"
      
platform:
  arch: amd64
  os: linux

pipeline:
  test:
    image: alpine/git
    image: java:8-jdk
    pull: true
    commands:
      - java -version
