kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux
  
steps:
  -  name: test
     image: alpine/git
     image: openjdk:11.0.2     
     pull: true
     
     commands:
       - chmod 777 ./Run.command
       - chmod 777 ./lib/Drivers/chromedriver
       - ./Run.command -run -project_location "Projects/DemoProject" -scenario "AngularJS_Support" -testcase "AngularJS_Test" -browser "Chrome"
       
services:
  selenium:
      image: selenium/standalone-chrome:3.141.59-vanadium
      
when:
    event:
      - push
      - tag
